language: python
dist: focal
python:
  - "3.8"
  - "3.9"
# command to install dependencies
before_install:
  - pip install -U pip
  - pip install -U pytest
  - pip install coverage
  - pip install poetry
install:
  #- pip install -U ".[dev]"
  #- pip install -r requirements.txt
  #- pip install coverage
  - poetry install --extras "dev"
# command to run tests
script:
  - poetry run coverage run -m pytest
after_success:
  - bash <(curl -s https://codecov.io/bash)
