language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
before_install:
  - pip install -U pip
  - pip install -U pytest
  - pip install coverage
install:
  - pip install
  #- pip install -r requirements.txt
  - pip install coverage
# command to run tests
script:
  - coverage run -m pytest
after_success:
  - bash <(curl -s https://codecov.io/bash)
