name: fars_cleaner
channels:
  - conda-forge
  - defaults
dependencies:
  - python >= 3.8
  - numpy
  - pandas
  - dask
  - distributed
  - tqdm
  - pooch >= 1.6.0
  - pathlib
  - requests
  - thefuzz
  - pyjanitor