name: fars_cleaner
channels:
  - conda-forge
  - defaults
dependencies:
  - python >= 3.6
  - numpy
  - pandas
  - dask
  - pyjanitor >= 0.23.1
  - tqdm
  - pooch >= 1.6.0
  - pathlib
  - requests
  - json