name: fars_cleaner
channels:
  - conda-forge
  - defaults
dependencies:
  - python >= 3.7
  - numpy
  - pandas
  - dask
  - distributed
  - tqdm
  - pooch >= 1.6.0
  - pathlib
  - requests
  - pip:
      - fuzzyfinder
      - pyjanitor