package:
  name: fars_cleaner
  version: "1.2.0"

source:
  git_rev:
  git_url: https://github.com/mzabrams/fars-cleaner

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    -

about:
  home: