name: CI

on: [push]

defaults:
  run:
    shell: bash

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, ubuntu-22.04, macos-12, macos-11, windows-latest]
        python-version: ['3.8', '3.9' ,'3.10']
        include:
          - os: windows-latest
            continue-on-error: true
          - os: ubuntu-20.04
            continue-on-error: true
          - os: ubuntu-22.04
            continue-on-error: true
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1.3.1
        with:
          version: 1.2.1
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install Dependencies
        run: poetry install --extras "dev"
      - name: Test with pytest
        run: poetry run pytest